# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImportLayerTree
                                 A QGIS plugin
 This plugin allows to import layers and groups from project files
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-25
        copyright            : (C) 2019 by Eloy Aldao
        email                : eloy.aldao@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImportLayerTree class from file ImportLayerTree.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ImportLayerTree import ImportLayerTree
    return ImportLayerTree(iface)
